  
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  
docker-build:
  stage: build
   # Build Docker image
  script:    
    
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Push the Docker image to Heroku Container Registry
    - docker build -t registry.heroku.com/tecevento-api/tecevento . 
    - docker push registry.heroku.com/tecevento-api
    #- heroku container:push web -a tecevento-api
    #- heroku container:release web -a tecevento-api