image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

deploy-master:
  stage: master
  script:
    - docker run -t -v $PWD:/app --workdir /app mcr.microsoft.com/dotnet/sdk:5.0 bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
    - docker build -t $CI_REGISTRY/tecevento-api/web .
    - docker push $CI_REGISTRY/tecevento-api/web   
    - heroku container:release web --app tecevento-api
  only:
    - master