  
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  
docker-build:
  stage: build
   # Build Docker image
  
  script:
    - apk update && apk add nodejs
    - apk add --update npm
    - npm i -g heroku        
    #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY    
    - echo $HEROKU_API_KEY | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY    
    # Push the Docker image to Heroku Container Registry
    #- docker build -t registry.heroku.com/tecevento-api/web . 
    #- docker push registry.heroku.com/tecevento-api/web
    - heroku container:push web -a tecevento-api
    - heroku container:release web -a tecevento-api