  
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  
docker-build:
  stage: build
   # Build Docker image
  script:    
      - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    # Push the Docker image to Heroku Container Registry
      - heroku container:push web -a tecevento-api
      - heroku container:release web -a tecevento-api